remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  
just_the_docs:
  toc:
    enabled: true
    depth: 6
    sticky: true

# Your custom domain
url: "https://docs.voukoderpro.com"  # Replace with your custom domain
baseurl: ""                          # Keep empty if it's root of domain
