remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

markdown: kramdown

kramdown:
  input: GFM
  auto_ids: true
  toc_levels: 1..6
  hard_wrap: false
  syntax_highlighter: rouge
  
just_the_docs:
  toc:
    enabled: true
    depth: 6
    sticky: true

url: "https://docs.voukoderpro.com"
baseurl: ""
